#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="Hack Nerd Font"
PADDING=3

# Define the properties of the bar
bar=(
  position=top
  notch_width=188
  height=32
  margin=0
  padding_left=23
  padding_right=23
  sticky=true
  color=$BASE
  display=main
)

sketchybar --bar "${bar[@]}"

# Define defaults of sketchybar
default=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$TEXT
  icon.padding_left=$PADDING
  icon.padding_right=$PADDING
  label.font="$FONT:Semibold:13.0"
  label.color=$SUBTEXT1
  label.padding_left=$PADDING
  label.padding_right=$PADDING
  padding_left=$PADDING
  padding_right=$PADDING
  background.height=30
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$ROSEWATER
  popup.background.color=$FLAMINGO
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
  --set chevron icon= label.drawing=off \
  --add item front_app left \
  --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    background.color=$MAUVE \
    background.corner_radius=5 \
    background.height=20 \
    background.width=20 \
    label.color=$TEXT \
    background.drawing=off \
    label="$sid" \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
  --set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
